[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "slight talent angle bunker give exhibit armor blossom lucky gap vanish dice noble toilet life birth coil state october opinion illness fever mountain six"
